# *Day 10 Statistics Sample T/Z Test*

In [2]:
import numpy as np
import pandas as pd
from scipy import stats 
from scipy.stats import norm,t
from scipy.stats import expon

1-sample z test/ 1 sample t test

- Used to check whether the difference betweent the sample mean and claim value can be ignored or not.
- Used to check whether the difference betweent the sample mean and claim value is statistically significant or not

In [65]:
df = pd.read_excel("/Users/gajendra06/Documents/Documents/CDAC_BDA/7_Advanced_Analytics_Using_Statistics/CDAC_DataBook.xlsx", sheet_name="faithful")

In [9]:
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [67]:
pip install fastexcel

Collecting fastexcel
  Downloading fastexcel-0.20.2-cp310-abi3-macosx_11_0_arm64.whl.metadata (7.2 kB)
Downloading fastexcel-0.20.2-cp310-abi3-macosx_11_0_arm64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 6.5 MB/s  0:00:007.6 MB/s eta 0:00:010:01
Installing collected packages: fastexcel
Successfully installed fastexcel-0.20.2
Note: you may need to restart the kernel to use updated packages.

In [71]:
conda install fastexcel

Jupyter detected...
2 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fastexcel

Current channels:

  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



Note: you may need to restart the kernel to use updated packages.

In [68]:

dl = pl.read_excel("/Users/gajendra06/Documents/Documents/CDAC_BDA/7_Advanced_Analytics_Using_Statistics/CDAC_DataBook.xlsx", sheet_name='faithful')

In [20]:
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

ssw.ztest(erupts,value=3.6,alternative='smaller')

(np.float64(-1.621495827018525), np.float64(0.05245567210775938))

1. Ho 'mu' >= 3.7 \
   Ha 'mu' < 3.7
2. CL = 95% = 0.95 \
   Los = 5% = 0.05
3. 1 Sample z test
4. TS, p-value

In [10]:
erupts = df.eruptions
xbar = np. mean(erupts)
n = len(erupts)
sd = np.std(erupts,ddof=1)

In [11]:
print(n)
print(xbar)

272
3.4877830882352936

In [13]:
# Transfoemed value of mean bar 
z = (xbar - 3.7)/(sd/n**0.5)

In [14]:
z

np.float64(-3.066461475706521)

In [15]:
norm.ppf(0.05)

np.float64(-1.6448536269514729)

In [16]:
norm.cdf(0.5)

np.float64(0.6914624612740131)

In [17]:
z = (xbar - 3.5)/(sd/n**0.5)

In [18]:
z

np.float64(-0.17653017833052984)

In [23]:
ssw.ztest(erupts,value=3.53, alternative="smaller")

(np.float64(-0.6100198729369251), np.float64(0.27092432161445423))

In [27]:
norm.cdf(z)

np.float64(0.2709243216144542)

In [25]:
z = (xbar - 3.53)/(sd/n**0.5)

In [26]:
z

np.float64(-0.6100198729369253)

In [28]:
norm.cdf(z)

np.float64(0.2709243216144542)

In [ ]:
# now my claim is the mean of the population will not exceed 3.37 
# Less than ('mu' < 3.37)
# what is test statistic?
# what will be the critical  value?

In [30]:
norm.ppf(0.95)

np.float64(1.644853626951472)

In [31]:
# find p-value
z = (xbar - 3.7)/(sd/n**0.5)
z

np.float64(-3.066461475706521)

In [32]:
1 - norm.cdf(1.7)

np.float64(0.044565462758543006)

1. MINIMUM WAITING TIME IS 75 MIN
   - TEST STATE
   - P-VALUE
   - 95% UB

In [33]:
# TEST STATE 
xbar = np.mean(df.waiting)
xbar

np.float64(70.8970588235294)

In [34]:
sd = np.std(df.waiting,ddof=1)

In [35]:
sd

13.594973789999392

In [36]:
z = (xbar - 75)/(sd/n**0.5)

In [37]:
z

np.float64(-4.977386527579324)

In [40]:
# p -value is 0 > 0.05 -> Ho rejected
norm.cdf(z)

np.float64(3.2224270495005785e-07)

In [42]:
# 
zc = norm.ppf(0.05)
zc

np.float64(-1.6448536269514729)

In [44]:
# 95% upper bound
xbar + 1.64*sd/n**0.5

# current mean that is xbar(70)

np.float64(72.24893766438854)

In [46]:
ssw.ztest(df.waiting,value=75,alternative='smaller')

(np.float64(-4.9773865275793225), np.float64(3.222427049500608e-07))

In [48]:
norm.cdf(z)

np.float64(3.2224270495005785e-07)

In [49]:
# Bangalore my people in Bangalore, take 45 minutes more Bangalore Bangalore Weather to be very cautious, whether it is B minus JRA minus B because I said that in Bangalore 45 minutes at least 40 minutes

In [50]:
# 10 Sample question on Test statestics with defender approach <Chatgpt>

# Sample Data of Faithful

In [51]:
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [52]:
df1 = df.iloc[20:60]
df2 = df.iloc[120:170]

In [54]:
erupt1 = df1.eruptions
erupt2 = df2.eruptions

In [56]:
np.mean(erupt1)

np.float64(3.44745)

In [57]:
np.mean(erupt2)

np.float64(3.4876399999999994)

Mean of erupt2 is atleast 0.12 more than the mean of erupt1

Ho: mean(erupt2) - mean(erupt1) >=0.12

Ha: mean(erupt2) - mean(erupt1) < 0.12

In [58]:
ssw.ztest(erupt2,erupt1,value=0.12, alternative='smaller')

(np.float64(-0.3196536558502502), np.float64(0.3746154475542464))

Travel in Blore is atleast 15 min more than Mumbai

Blore
Sample size 50
Avg time 45
Std Dev 10.5

Mumbai
Sample size 60
Avg time 34
Std Dev 5.6

In [64]:
import polars as pl

# 1. Create or read a DataFrame
df = pl.DataFrame(
    {
        "id": [1, 2, 3, 4],
        "category": ["A", "B", "A", "B"],
        "value": [10.5, 20.0, 15.0, 30.2],
    }
)

# 2. Filter and aggregate (Expression Syntax)
result = (
    df.filter(pl.col("category") == "A")
    .group_by("category")
    .agg(
        pl.col("value").sum().alias("total_value"),
        pl.col("id").count().alias("count")
    )
)

print(result)

shape: (1, 3)
┌──────────┬─────────────┬───────┐
│ category ┆ total_value ┆ count │
│ ---      ┆ ---         ┆ ---   │
│ str      ┆ f64         ┆ u32   │
╞══════════╪═════════════╪═══════╡
│ A        ┆ 25.5        ┆ 2     │
└──────────┴─────────────┴───────┘

In [63]:
import polars as pl

In [69]:
dl.head()

shape: (5, 2)
┌───────────┬─────────┐
│ eruptions ┆ waiting │
│ ---       ┆ ---     │
│ f64       ┆ i64     │
╞═══════════╪═════════╡
│ 3.6       ┆ 79      │
│ 1.8       ┆ 54      │
│ 3.333     ┆ 74      │
│ 2.283     ┆ 62      │
│ 4.533     ┆ 85      │
└───────────┴─────────┘

In [73]:
dl.tail(30)

shape: (30, 2)
┌───────────┬─────────┐
│ eruptions ┆ waiting │
│ ---       ┆ ---     │
│ f64       ┆ i64     │
╞═══════════╪═════════╡
│ 4.933     ┆ 86      │
│ 2.9       ┆ 63      │
│ 4.583     ┆ 85      │
│ 3.833     ┆ 82      │
│ 2.083     ┆ 57      │
│ …         ┆ …       │
│ 4.117     ┆ 81      │
│ 2.15      ┆ 46      │
│ 4.417     ┆ 90      │
│ 1.817     ┆ 46      │
│ 4.467     ┆ 74      │
└───────────┴─────────┘

In [74]:
print(dl)

shape: (272, 2)
┌───────────┬─────────┐
│ eruptions ┆ waiting │
│ ---       ┆ ---     │
│ f64       ┆ i64     │
╞═══════════╪═════════╡
│ 3.6       ┆ 79      │
│ 1.8       ┆ 54      │
│ 3.333     ┆ 74      │
│ 2.283     ┆ 62      │
│ 4.533     ┆ 85      │
│ …         ┆ …       │
│ 4.117     ┆ 81      │
│ 2.15      ┆ 46      │
│ 4.417     ┆ 90      │
│ 1.817     ┆ 46      │
│ 4.467     ┆ 74      │
└───────────┴─────────┘