In [104]:
import pandas as pd
import numpy as np
import polars as pl
import scipy
from scipy import stats
from scipy.stats import binom, poisson, norm, t
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title,xlabel,ylabel

In [ ]:
df = pl.read_excel("")

# Paired Test

In [105]:
before = np.array([12,14,10,9,8,13])
after = np.array([11.8,9.7,11.3,8.2,7.2,12.3])

- Ho | before - after  | : (excpected to be high, Positive Difference)
- Ha | after  - before | : (Output will be negative)

In [106]:
d = (before - after)

In [107]:
d

array([ 0.2,  4.3, -1.3,  0.8,  0.8,  0.7])

In [108]:
np.mean(d)

np.float64(0.9166666666666665)

In [150]:
import statsmodels
from statsmodels import stats
import statsmodels.api as sm
from statsmodels.stats import weightstats as ssw
from statsmodels.formula.api import ols

# Import the required function from statsmodels library
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Now you can use the function (note: correct function name is pairwise_tukeyhsd, not pairwise_tukeysd)
print(pairwise_tukeyhsd(df.Col2, df.Col1))

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     A      B  10.2381  0.011  2.2177 18.2585   True
     A      C  -0.6786 0.9765 -8.9154  7.5582  False
     B      C -10.9167 0.0051  -18.65 -3.1834   True
----------------------------------------------------

Multiple Comparison of Means - Tukey HSD, FWER=0.05 
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     A      B  10.3968 0.0107  2.2907 18.5029   True (NUll Hypothesis True)
     A      C   4.4107 0.3919 -3.9141 12.7355  False
     B      C  -5.9861 0.1549 -13.802  1.8298  False
----------------------------------------------------

In [110]:
ssw.ttost_paired(before,after, low=2,upp=2)

(np.float64(0.8954696830206994),
 (np.float64(-1.4413160909218492),
  np.float64(0.8954696830206994),
  np.float64(5.0)),
 (np.float64(-1.4413160909218492),
  np.float64(0.10453031697930062),
  np.float64(5.0)))

In [111]:
scipy.stats.ttest_1samp(before-after,popmean=2,alternative='less')

TtestResult(statistic=np.float64(-1.4413160909218492), pvalue=np.float64(0.10453031697930062), df=np.int64(5))

In [112]:
# BTS calculation of above commmands/Equation
(np.mean(d)-2)/((np.std(d,ddof=1))/6**0.5)

np.float64(-1.4413160909218492)

In [113]:
t.cdf(-1.4413160909218492,5)

np.float64(0.10453031697930062)

- 4th Step
  
======================================================================================
# ANOVA test 
======================================================================================
- (ANalysis of VAraince)
   -

In [148]:
dfA = pd.DataFrame({'Col1':np.repeat('A',7),'Col2':np.random.randint(10,30,7)})
dfB = pd.DataFrame({'Col1':np.repeat('B',9),'Col2':np.random.randint(20,40,9)})
dfC = pd.DataFrame({'Col1':np.repeat('C',8),'Col2':np.random.randint(15,30,8)})
df = pd.concat([dfA,dfB,dfC])

In [115]:
df

  Col1  Col2
0    A    20
1    A    11
2    A    14
3    A    14
4    A    16
5    A    22
6    A    20
0    B    33
1    B    22
2    B    21
3    B    22
4    B    37
5    B    24
6    B    28
7    B    29
8    B    25
0    C    20
1    C    23
2    C    28
3    C    16
4    C    27
5    C    28
6    C    19
7    C    29

In [149]:
# Import the necessary function from statsmodels
# ordinary list square
from statsmodels.formula.api import ols

# Now you can use the ols function
mod1 = ols('Col2 ~ Col1', df).fit()

In [117]:
tb1 = sm.stats.anova_lm(mod1)

In [118]:
tb1

            df      sum_sq     mean_sq         F    PR(>F)
Col1       2.0  408.849206  204.424603  8.442578  0.002039
Residual  21.0  508.484127   24.213530       NaN       NaN

In [119]:
# Import the required function from statsmodels library
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Now you can use the function (note: correct function name is pairwise_tukeyhsd, not pairwise_tukeysd)
print(pairwise_tukeyhsd(df.Col2, df.Col1))

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     A      B  10.0635 0.0016   3.813  16.314   True
     A      C   7.0357 0.0301  0.6165 13.4549   True
     B      C  -3.0278 0.4291 -9.0546   2.999  False
----------------------------------------------------

# Data Anova

In [120]:
df = pd.read_excel("/Users/gajendra06/Downloads/data_anova.xlsx")

In [121]:
df.head()

  Col1  Col2
0    A    10
1    A    23
2    A    14
3    A    25
4    A    22

In [122]:
df.tail()

   Col1  Col2
19    C    19
20    C    29
21    C    27
22    C    17
23    C    24

In [123]:
df.count()

Col1    24
Col2    24
dtype: int64

In [124]:
grp1 = df.groupby('Col1')

In [125]:
# mean of A, B, C from Column 2
grp1.agg('mean')

           Col2
Col1
A     16.714286
B     31.222222
C     23.250000

In [126]:
# Sample mean saving mean 
sm = grp1.agg('mean')

In [127]:
# Grand mean 
gm = np.mean(df.Col2)

In [128]:
gm

np.float64(24.333333333333332)

In [129]:
sm.loc['A']

Col2    16.714286
Name: A, dtype: float64

In [130]:
sm.loc['B']

Col2    31.222222
Name: B, dtype: float64

In [131]:
sm.loc['C']

Col2    23.25
Name: C, dtype: float64

In [132]:
7*(sm.loc['A'] - gm)**2 + 9*(sm.loc['B'] - gm)**2 + 8*(sm.loc['C'] - gm)**2

Col2    842.849206
dtype: float64

In [133]:
print(df)

   Col1  Col2
0     A    10
1     A    23
2     A    14
3     A    25
4     A    22
5     A    11
6     A    12
7     B    26
8     B    39
9     B    29
10    B    39
11    B    31
12    B    32
13    B    38
14    B    22
15    B    25
16    C    21
17    C    23
18    C    26
19    C    19
20    C    29
21    C    27
22    C    17
23    C    24

In [134]:
samp_mean = grp1.agg('mean')

In [135]:
samp_mean

           Col2
Col1
A     16.714286
B     31.222222
C     23.250000

In [136]:
grand_mean = np.mean(df.Col2)

In [137]:
grand_mean

np.float64(24.333333333333332)

In [138]:
sampA = df.Col2[np.where(df.Col1 =='A')[0]]
sampB = df.Col2[np.where(df.Col1 =='B')[0]]
sampC = df.Col2[np.where(df.Col1 =='C')[0]]

In [140]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]
df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})

In [141]:
df

    Resp  Factor1 Factor2
0     34        1       R
1     43        1       D
2     57        1       R
3     40        1       D
4     85        2       R
5     68        2       D
6     67        2       R
7     53        2       D
8     41        3       R
9     24        3       D
10    42        3       R
11    52        3       D

In [142]:
df.Resp.mean()

np.float64(50.5)

In [143]:
df.count()

Resp       12
Factor1    12
Factor2    12
dtype: int64

In [144]:
df.Factor1.count()

np.int64(12)

In [145]:
model = ols('Resp~Factor1+Factor2',df).fit()

In [151]:
res=sm.stats.anova_lm(model)

In [152]:
res

           df       sum_sq     mean_sq         F    PR(>F)
Factor2   1.0   176.333333  176.333333  0.543765  0.479659
Factor1   1.0    28.125000   28.125000  0.086730  0.775056
Residual  9.0  2918.541667  324.282407       NaN       NaN

When the change of the level of 1 Factor has a difference impact on the level of other factor