# Types of data

#### 1. Qualitative data: Mostly in strings or words
#### 2. Quantitative data: Mostly in numbers

1. Quantitative Data 
- Continuous Data:
  - Continuous data is the one where possibility of decimal point cannot be ruled out.
  - Will always be the result of measurememt (for measurement we need instrument)
  - It will always be expressed in "mlt"
- Discrete Data:
  - Descrete data will never have decimal point.
  - It will always be a result of counting.
  - If n*p and n*(1-p)>10, then descrete data can be considered as continuous. (n -> sample size, p -> proportion)
  - For large sample size, descrete and continuous can be considered to be same.
- Any rating or ranking even if it is a number will be considered as categorical data.

Specifically in regression:
Type of scale:
1. Nominal: Got multiple category, but we may choose one or more.(there is no logical order) (Categorical data)
2. Ordinal: Ranked or rating. (It has logical order)(Comparision) (Categorical Data)
3. Interval: Zero does not mean absence of measurement, so mathematical calculations will be restricted. You compare the values but cannot take the ratio of the values
4. Ratio:

# Descriptive Statistics
## 1. Data Summarization
## 2. Data Visualization

# Inferential Statistics

# Predictive Statistics (Modelling) (PML)

# Descriptive Statistics
## 1. Data Summarization (counts, proportion, percentage, and cumulative of all)

In [2]:
import numpy as np
import pandas as pd

In [84]:
df = pd.read_excel("CDAC_DataBook.xlsx", sheet_name="ERPData")
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [85]:
x1 = df.MaterialID

In [86]:
len(np.unique(x1))

6

In [87]:
np.unique(x1, return_counts=True)

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [88]:
x1.value_counts()

MaterialID
TMI-43T    15
AXCP-78    11
DDBN-89     8
SDRT-67     6
GCVB-79     5
LXCV-21     5
Name: count, dtype: int64

In [89]:
df1 = x1.value_counts().reset_index()
df1

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    GCVB-79      5
5    LXCV-21      5

In [90]:
df1['prop'] = df1['count']/sum(df1["count"])

In [91]:
df1

  MaterialID  count  prop
0    TMI-43T     15  0.30
1    AXCP-78     11  0.22
2    DDBN-89      8  0.16
3    SDRT-67      6  0.12
4    GCVB-79      5  0.10
5    LXCV-21      5  0.10

In [92]:
df1['pct'] = df1['prop']*100

In [93]:
df1

  MaterialID  count  prop   pct
0    TMI-43T     15  0.30  30.0
1    AXCP-78     11  0.22  22.0
2    DDBN-89      8  0.16  16.0
3    SDRT-67      6  0.12  12.0
4    GCVB-79      5  0.10  10.0
5    LXCV-21      5  0.10  10.0

In [94]:
df1['CumPct'] = np.cumsum(df1['pct'])
df1

  MaterialID  count  prop   pct  CumPct
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    GCVB-79      5  0.10  10.0    90.0
5    LXCV-21      5  0.10  10.0   100.0

In [95]:
df1.sort_values("count", ascending=False)

  MaterialID  count  prop   pct  CumPct
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    GCVB-79      5  0.10  10.0    90.0
5    LXCV-21      5  0.10  10.0   100.0

## Central Tendency -> Mean, Median, Mode
## Dispersion or variation or spread -> range, inter quartile range, variance and standard deviation
## Shape -> skewness and kurtosis

# Central Tendency
1. Mean: avg
- Mean should be used only when there are no extreme valeus in the dataset.
- Mean should be use categoricald only when the data is normally/symmetrically distributed.
2. Median: Odd number (pick the middle value) Even number (pick n/2 and (n+1)/2)
- Median can be used in all circumstances.
3. Mode: Number that appears most number of times.
- It is the only parameter which can be caluclated for qualitative data and it can have more than 1 value.

In [110]:
x1=np.array([3,4,5,6])
x2=np.array([20,18,9,12])
sum(x1*x2/sum(x2)) # Weighted mean

np.float64(4.220338983050848)

In [3]:
df = pd.read_excel("CDAC_DataBook.xlsx", sheet_name="faithful")
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [9]:
df['eruptions']

0      3.600
1      1.800
2      3.333
3      2.283
4      4.533
       ...
267    4.117
268    2.150
269    4.417
270    1.817
271    4.467
Name: eruptions, Length: 272, dtype: float64

In [7]:
df['eruptions'].mean()

np.float64(3.4877830882352936)

In [8]:
df['eruptions'].median()

np.float64(4.0)

In [10]:
df['eruptions'].mode()

0    1.867
1    4.500
Name: eruptions, dtype: float64

In [13]:
from scipy import stats
stats.mode(df.eruptions)

ModeResult(mode=np.float64(1.867), count=np.int64(8))

In [21]:
from collections import Counter
Counter(df.eruptions).most_common()

[(1.867, 8),
 (4.5, 8),
 (1.833, 7),
 (4.7, 6),
 (1.75, 6),
 (4.8, 6),
 (4.0, 6),
 (4.533, 5),
 (4.083, 5),
 (3.833, 5),
 (4.333, 5),
 (3.6, 4),
 (1.8, 4),
 (4.35, 4),
 (4.25, 4),
 (1.883, 4),
 (2.0, 4),
 (4.167, 4),
 (4.417, 4),
 (4.6, 4),
 (4.15, 4),
 (4.583, 4),
 (3.917, 3),
 (1.967, 3),
 (2.017, 3),
 (4.567, 3),
 (2.1, 3),
 (4.633, 3),
 (1.817, 3),
 (1.983, 3),
 (4.933, 3),
 (2.2, 3),
 (4.367, 3),
 (4.233, 3),
 (4.45, 3),
 (3.333, 2),
 (2.167, 2),
 (3.85, 2),
 (4.433, 2),
 (4.3, 2),
 (4.467, 2),
 (4.033, 2),
 (4.833, 2),
 (2.233, 2),
 (4.133, 2),
 (4.1, 2),
 (4.067, 2),
 (3.95, 2),
 (4.817, 2),
 (4.667, 2),
 (4.9, 2),
 (1.783, 2),
 (3.767, 2),
 (1.917, 2),
 (2.033, 2),
 (2.4, 2),
 (3.567, 2),
 (3.5, 2),
 (1.933, 2),
 (2.083, 2),
 (2.417, 2),
 (2.25, 2),
 (4.267, 2),
 (4.117, 2),
 (1.85, 2),
 (4.283, 2),
 (2.283, 1),
 (2.883, 1),
 (1.95, 1),
 (4.2, 1),
 (1.6, 1),
 (3.45, 1),
 (3.067, 1),
 (3.367, 1),
 (4.783, 1),
 (3.317, 1),
 (4.716, 1),
 (1.733, 1),
 (4.883, 1),
 (3.717, 1),
 (1.667, 1),
 (4.317, 1),
 (4.4, 1),
 (2.067, 1),
 (5.067, 1),
 (3.883, 1),
 (2.633, 1),
 (4.517, 1),
 (3.75, 1),
 (2.483, 1),
 (4.05, 1),
 (4.85, 1),
 (3.683, 1),
 (4.733, 1),
 (2.3, 1),
 (1.7, 1),
 (2.317, 1),
 (2.617, 1),
 (2.267, 1),
 (4.65, 1),
 (2.8, 1),
 (4.383, 1),
 (3.733, 1),
 (5.1, 1),
 (5.033, 1),
 (3.967, 1),
 (2.367, 1),
 (5.0, 1),
 (4.617, 1),
 (2.183, 1),
 (3.966, 1),
 (4.366, 1),
 (2.383, 1),
 (3.417, 1),
 (4.483, 1),
 (4.55, 1),
 (4.183, 1),
 (2.217, 1),
 (2.333, 1),
 (2.35, 1),
 (2.9, 1),
 (2.133, 1),
 (3.817, 1),
 (4.767, 1),
 (4.75, 1),
 (2.15, 1)]

# Dipersion/variation (Spread of data)
1. Range:
   - Can get affected by the outliers.
   - Even if there are no outliers it only considers the first and last value and neglects other.
2.  Inter quartile range (Percentile)
   - i=1+(n-1)*p/100
   - 75th percentile - 25th percentile
   - As the variations in data decrease the value of standard deviation and variance also decrease.
Pop variance
Pop std dev
Sample variance
Sample std dev
Coefficient of Variance (dimension less)

In [22]:
# Range
x1 = df.eruptions
max(x1) - min(x1)

3.4999999999999996

In [23]:
np.ptp(x1)

np.float64(3.4999999999999996)

In [24]:
IQR = np.percentile(x1,75) - np.percentile(x1,25)
IQR

np.float64(2.2915)

In [25]:
x1 = [1,1,2,2,2,3,3,3,3,4,4,5,5,5,5,6,6,6,7,7,8,9]
len(x1)

22

In [33]:
x2 = np.random.normal(loc=50, scale=15, size=1990)
x2

array([69.47192217, 27.84848179, 69.46368259, ..., 35.43711962,
        0.98963341, 16.02662075])

In [39]:
import pandas as pd
import numpy as np

np.random.seed(42)

data = np.random.normal(loc=50, scale=15, size=1990)

outliers = np.array([5000, 5200, 5500, 5800, 6000, 6200, 6500, 6800, 7000, 7200])

data_list = np.concatenate([data, outliers])

df = pd.DataFrame(data_list, columns=['Values'])
q1 = df['Values'].quantile(0.25)
q3 = df['Values'].quantile(0.75)
iqr = q3 - q1

lower_fence = q1 - 1.5 * iqr
upper_fence = q3 + 1.5 * iqr

print(f"Q1: {q1}")
print(f"Q3: {q3}")
print(f"IQR: {iqr}")
print(f"Upper Outlier Threshold: {upper_fence}")
print(f"Lower Outlier Threshold: {lower_fence}")

Q1: 40.77104154172274
Q3: 60.44377453211364
IQR: 19.672732990390905
Upper Outlier Threshold: 89.9528740177
Lower Outlier Threshold: 11.26194205613638

In [43]:
x2 = [4,3,6,5,7,9,4,8,7,3]

In [44]:
#pop variance
np.var(x2)

np.float64(4.04)

In [45]:
# pop std dev
np.std(x2)

np.float64(2.009975124224178)

In [47]:
# Sample variance
np.var(x2, ddof=1)

np.float64(4.488888888888889)

In [48]:
# Sample std dev
np.std(x2,ddof=1)

np.float64(2.1186998109427604)

# Shape -> skewness and kurtosis
1. Skewness:
- In graph, if peak is on the left side
    - distribution is skewed to right
    - positively skewed
    - skewness > 0
- In graph, if peak is in the center
    - distribution is symmetric
    - skewness = 0
- In graph, if the peak is on the right side
    - distribution is skewed to left
    - negatively skewed
    - skewness < 0

# Probability Distribution
1. Distribution for discrete data.
- Binomial Distribution (Used when there are only two possible occurrences and probability of occurrences is known)
  Mean no of occurrences equal to n*p
  e.g. Chances of rain on any given day in June in Mumbai is 0.7
  If I am in Mumbai for 15 days, what is the probability that
  a. It rains for exactly 10 days.
  b. It rains for maximum 10 days.
  c. It rains for minimum 10 days.
- Poisson Distribution (Used when we are more concerened about frequency of an event -> how many times it occur)
  
2. Distribution for continuous data
- Exponential Distribution
  It is used to model the time gap between two successive events.
- Normal Distribution
  It is a normal bell shape curve (to define it we need mean and std dev)
  Standard Normal Curve (mean=0 and std_dev=1)
- Students t distribution
  It is used when the population standard deviation is not known, what we know is the sample standard deviation
  Necessarily used when the sample size is less than equal to 30
  For small samples, normal distribution cannot be used
  e.g. 200 incidents happening in a year so mean time between failure (MTBF) is (356*24)/200 unit is hours/incident
  1 incident-> 1/(356*24)/200 is rate of failure

In [2]:
# Binomial Distribution
from scipy.stats import binom
# binom.pmf (Probability mass function) (Used to find the probability for an exact number)
# binom.cdf (Cumulative Distribution function) (Used when to find probability of upto a particular number) (e.g. 0-1-2-3-4-5 -> upto 5)
# binom.pf

In [67]:
a = binom.pmf(10,15,0.7)

In [56]:
1 - binom.cdf(10,15,0.7)

np.float64(0.5154910592268429)

In [64]:
x=np.arange(0,16)

In [ ]:
plt.figure(figsize=(8, 5))
plt.bar(x, a, color='skyblue', edgecolor='black')

plt.xlabel('Number of Successes')
plt.ylabel('Probability')
plt.title(f'Binomial Distribution')
plt.xticks(x)
plt.grid(axis='y', linestyle='--', alpha=0.7)

In [1]:
# Poission Distribution
# Avg number of occurrences is 15. What is the probability of
# a. exactly 12 incidents taking place today
from scipy.stats import poisson
poisson.pmf(12,15)

np.float64(0.08285923436864541)

In [72]:
# b. upto 12 incidents take place
poisson.cdf(12,15)

np.float64(0.2676110333925769)

In [73]:
# c. minimum 12 incidents take place
1 - poisson.cdf(11,15)

np.float64(0.8152482009760685)

In [76]:
poisson.sf(11,15)

np.float64(0.8152482009760685)

In [77]:
from scipy.stats import norm ,t

In [79]:
norm.cdf(14,16,2.3)

np.float64(0.19226902649831168)

In [87]:
z=(14-16)/2.3
norm.cdf(z)

np.float64(0.19226902649831168)

In [80]:
1-norm.cdf(14,16,2.3)

np.float64(0.8077309735016883)

In [86]:
norm.cdf(17,16,2.3) - norm.cdf(13,16,2.3)

np.float64(0.5720823773874264)

In [ ]:
# Which graph will you plot whether gender will effect on the salary.

In [3]:
import scipy
from scipy import stats
from scipy.stats import binom, poisson, norm, t

In [4]:
norm.cdf(43,45,2.8)

np.float64(0.2375252620269765)

In [6]:
z=(43-45)/2.8
z

-0.7142857142857143

In [7]:
norm.cdf(z,0,1)

np.float64(0.2375252620269765)

In [8]:
norm.cdf(z)

np.float64(0.2375252620269765)

In [9]:
norm.cdf(1.73)

np.float64(0.9581848623864051)

In [31]:
# Students t distribution
z = (14-15.3)/1.8
z

-0.7222222222222227

In [32]:
t.cdf(z,1499) # second argument is degree of freedom which is "sample_size-1"

np.float64(0.2351352562574976)

In [33]:
norm.cdf(z)

np.float64(0.23507893142883468)

In [ ]:
# How important is agility in today's time

In [37]:
# Exponential Distribution
from scipy.stats import expon

In [38]:
expon.cdf(100,scale=43.8)

np.float64(0.898032895521957)

In [43]:
(24/80)*60

18.0

In [47]:
expon.cdf(1,scale=0.3)

np.float64(0.9643260066527476)

In [ ]:
# On an avg johnson sir comes 30 times in a 45 days course (1 day course is 8 hours). What is the probability that he will come today.

In [58]:
360/30

12.0

In [59]:
expon.cdf(8,scale=12)

np.float64(0.486582880967408)

In [ ]:
# Binomial : Two possibilities and probability
# Poisson: Two possibilities and frequency
# Normal : Bell shape curve, written normal (Mean and standard deviation and small sample is given)
# Exponential: Time gaps between two events.